# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

name: Windows

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          #http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          rtools-version: '42'
      
      - name: Install JAGS on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        
        run: |
          $u = 'https://github.com/TathagataChattopadhyay2000/EDITS/releases/download/v1.0.0/JAGS-4.3.1.exe'
          $p = "$env:RUNNER_TEMP\JAGS-4.3.1.exe"
          Invoke-WebRequest $u -OutFile $p
          Start-Process $p -ArgumentList '/S' -Wait
          Add-Content -Path $env:GITHUB_ENV -Value 'JAGS_HOME=C:\Program Files\JAGS\JAGS-4.3.1'


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install bhmbasket
        shell: bash
        run: R CMD INSTALL --preclean .

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true